spring:
  application:
    name: OPDKukushiki
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
rabbit:
  queue:
    nameForTranscribe: transcribeService