spring:
  application:
    name: OPDKukushiki
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  data:
    redis:
      host: localhost
      port: 6379
rabbit:
  queue:
    nameForTranscribe: transcribeService